baseURL = "https://iglotov.com/"
languageCode = "en-us"
title = "Ilia Glotov"
theme = "hugo-identity-theme"

# Disable unnecessary kinds
#disableKinds = ["page", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

# Enter your tracking code to enable Google Analytics
#googleAnalytics = "UA-163774673-1"
#googleAnalytics = "G-97PFJE93Q5"

[params]
  # Images settings
  # Icons, backgrounds and avatars folders are placed in theme's static/images folder.
  # You may place your images in corresponding folders and then set only filenames below to
  # change page's appearance

  # Site icons
  description = "personal page"
  name = "Ilia Glotov"
  favicon_ico = "favicon.ico"
  #favicon_ico_sizes = "16x16 32x32"
  favicon_ico_sizes = "16x16"
  appleicon = "apple.png"

  # Additional options to supplement icons served
  favicon_png = "favicon.png"
  favicon_png_sizes = "96x96"
  #favicon_svg = "favicon.svg"

  # Link custom assets relative to /static
  #custom_js  = [""]
  #custom_css = ["background.css", "icons.css"]
  custom_css = ["background.css"]

  # Customization switches
  # Overwrite FontAwesome: see icons.css
  #custom_icons = true
  # Overwrite background: see background.css
  custom_background = true

  # Personal data
  [params.personal]
    # If name is not set, author is used
    name = "Ilia Glotov"
    # Avatars can be written to images/avatars/
    avatar = "iglotov.jpg"
    position = "DevOps Engineer @ [Sxipher](https://sxipher.ai)"
    livesIn = "[Novi Sad, Serbia](https://maps.app.goo.gl/5aZKrqcaiZnKmiQdA)"
    scope = [
        #"[![WBW Flag](/images/icons/White-blue-white_flag_w_border.png \"Fuck the war!\")](https://en.wikipedia.org/wiki/White-blue-white_flag)"
      ]
    biography = """[Expat](https://en.wikipedia.org/wiki/White-blue-white_flag) (🇷🇺→🇬🇪→🇷🇸); proud [father of three](https://imgs.xkcd.com/comics/natural_parenting.png).
    I recently quit the [systems engineer](https://imgs.xkcd.com/comics/tools.png) position at [SOFTSWISS](https://www.softswiss.com/).
    [Fast learner](https://imgs.xkcd.com/comics/ten_thousand.png) (but systematic enough); a [security enthusiast](https://imgs.xkcd.com/comics/security.png);
    I have significant experience with Linux, various monitoring
    and configuration management tools, and Linux servers/databases/web
    apps troubleshooting. I previously worked as a DevOps engineer at
    [Vsemayki.ru (the great place to replace all this boring IT merch)](https://vsemayki.ru),
    [supl.biz (growing b2b marketplace)](https://supl.biz), [cbr.ru (some uncommon bank)](https://cbr.ru),
    systems administrator at [tsu.ru (cozy Siberian university)](https://tsu.ru),
    and many more outstanding companies. Seen some stuff."""

  # Contact form settings

  [params.contact]
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!

    email = "nomail@example.com"

    # It is possible to substitute formspring with other providers
    # as an example the mailout plugin from caddy.
    # Provide the post URL for the form and depending on the provider
    # add some custom JS script to finish the implementation.

    #postURL = "https://formspree.io/nodata"

    enable = false
    title = "Touch Me!"
    namePlaceholder = "Name"
    emailPlaceholder = "Email"
    messagePlaceholder = "Message"
    buttonText = "Send it"
    success = "Thank you for contacting me."
    error = "Message could not be send. Please contact me in some other way."

    # Google invisible captcha
    #[params.contact.captcha]
      #sitekey = ""


    # Add optional form fields to identify contact forms.
    #[[params.contact.fields.hidden]]
    #  name = "someID"
    #  value = "example.com"

    #[[params.contact.fields.hidden]]
    # Special values for name such as "page" and "site" will be autofilled
    #  name = "page"

  # Social settings
  # You may change these with your social links or add others

  #[[params.social]]
    #title = "Email"
    #icon = "fa-envelope-square"
    #link = "mailto:?to=writeme at iglotov.ru&subject=email from website&body=Please replace \" at \" with \"@\" in the recipient address. Thanks."
    #target = "_blank"

  [[params.social]]
    title = "CV"
    icon = "fa-file-o"
    link = "https://iglotov.com/cv.pdf"
    #target = "_blank"

  [[params.social]]
    title = "GPG pubkey"
    icon = "fa-lock"
    link = "https://iglotov.com/pubkey.asc"
    #target = "_blank"

  [[params.social]]
    title = "LinkedIn"
    icon = "fa-linkedin-square"
    link = "https://www.linkedin.com/in/iglotov/"
    #target = "_blank"

  [[params.social]]
    title = "Schedule a meeting"
    icon = "fa-calendar"
    link = "https://calendly.com/iglotov/30min"
    #target = "_blank"

  [[params.social]]
    title = "Telegram"
    icon = "fa-paper-plane-o"
    link = "https://telegram.me/iglotov"
    #target = "_blank"

  [[params.social]]
    title = "Github"
    icon = "fa-github-square"
    link = "https://github.com/iglotov"
    #target = "_blank"

  #[[params.social]]
    #title = "Instagram"
    #icon = "fa-instagram"
    #link = "https://www.instagram.com/ilya.glotov/"
    #target = "_blank"

  # Footer settings
  [params.footer]
    # If copyright is not set, author is used
    copyright = "Ilia Glotov"

  # Page license
  [params.license]
    link = "https://creativecommons.org/licenses/by-sa/4.0/legalcode"
    name = "CC-BY-SA-4.0"

  # Credits
  [[params.credits]]
    # Title is used as URL text
    title = "HTML5UP"
    # Text will be used to explain the credit
    text = "Design by"
    link = "https://html5up.net"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"
  #  # Track all subdomains with "*.example.com"
  #  domain = "www.example.com"
  #  # Optional integrity check hash
  #  hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

